using UnityEngine;

public class LUTBeamManager : MonoBehaviour
{
    public Texture[] gobos;
    public string AutoGenerateDirectory = "Assets/LUTBeam Generated";
    public string prefix = "";
    public int LUTResolution = 1024;
    public int GoboResolution = 512;
}
