using System.IO;
using UnityEditor;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace LUTBeam.Editor
{
    [CustomEditor(typeof(LUTBeamManager))]
    public sealed class LUTBeamManagerEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();
            GUILayout.Space(8f);

            LUTBeamManager manager = (LUTBeamManager)target;
            using (new EditorGUI.DisabledScope(manager.gobos == null || manager.gobos.Length == 0))
            {
                if (GUILayout.Button("Generate Texture Arrays"))
                    GenerateTextureArrays(manager);
            }
        }

        private static void GenerateTextureArrays(LUTBeamManager manager)
        {
            Texture[] gobos = manager.gobos;
            if (gobos == null || gobos.Length == 0)
                return;

            Texture2D[] goboTextures = new Texture2D[gobos.Length];
            Texture2D[] lutTextures = new Texture2D[gobos.Length];

            for (int i = 0; i < gobos.Length; i++)
            {
                goboTextures[i] = gobos[i] as Texture2D;
                if (goboTextures[i] == null)
                {
                    Debug.LogError("Every LUTBeam gobo must be a Texture2D.", manager);
                    return;
                }
            }

            Shader generatorShader = Shader.Find("LUTBeam/GoboLookupGenerator");
            if (generatorShader == null)
            {
                Debug.LogError("Could not find the LUTBeam gobo lookup generator shader.", manager);
                return;
            }

            Material material = new Material(generatorShader);
            for (int i = 0; i < goboTextures.Length; i++)
            {
                RenderTexture temporary = new RenderTexture(
                    manager.LUTResolution,
                    manager.LUTResolution,
                    32,
                    RenderTextureFormat.ARGBFloat);

                material.SetTexture("_MainTex", goboTextures[i]);
                Shader.SetGlobalFloat("_Supersample", 1f);
                Graphics.Blit(null, temporary, material);
                Shader.SetGlobalFloat("_Supersample", 0f);

                RenderTexture previous = RenderTexture.active;
                RenderTexture.active = temporary;
                Texture2D lookup = new Texture2D(
                    manager.LUTResolution,
                    manager.LUTResolution,
                    TextureFormat.RGBAFloat,
                    false);
                lookup.ReadPixels(
                    new Rect(0, 0, manager.LUTResolution, manager.LUTResolution),
                    0,
                    0);
                lookup.Apply();
                RenderTexture.active = previous;
                temporary.Release();
                DestroyImmediate(temporary);

                for (int x = 0; x < manager.LUTResolution; x++)
                {
                    for (int y = 0; y < manager.LUTResolution; y++)
                    {
                        Color color = lookup.GetPixel(x, y);
                        color.r = Mathf.LinearToGammaSpace(color.r);
                        color.g = Mathf.LinearToGammaSpace(color.g);
                        color.b = Mathf.LinearToGammaSpace(color.b);
                        lookup.SetPixel(x, y, color);
                    }
                }

                lookup.Apply();
                lutTextures[i] = lookup;
            }

            TextureFormat format = TextureFormat.BC4;
            Texture2DArray goboArray = new Texture2DArray(
                manager.GoboResolution,
                manager.GoboResolution,
                gobos.Length,
                format,
                false,
                false);
            Texture2DArray lutArray = new Texture2DArray(
                manager.LUTResolution,
                manager.LUTResolution,
                gobos.Length,
                format,
                false,
                false);

            for (int i = 0; i < gobos.Length; i++)
            {
                CopyCompressedSlice(goboTextures[i], manager.GoboResolution, format, goboArray, i);
                CopyCompressedSlice(lutTextures[i], manager.LUTResolution, format, lutArray, i);
                DestroyImmediate(lutTextures[i]);
            }

            DestroyImmediate(material);

            if (!Directory.Exists(manager.AutoGenerateDirectory))
            {
                Directory.CreateDirectory(manager.AutoGenerateDirectory);
                AssetDatabase.Refresh();
            }

            Scene scene = SceneManager.GetActiveScene();
            string prefix = string.IsNullOrWhiteSpace(manager.prefix) ? "" : " " + manager.prefix;
            string goboPath = $"{manager.AutoGenerateDirectory}/{scene.name}{prefix} - Gobo Textures.asset";
            string lutPath = $"{manager.AutoGenerateDirectory}/{scene.name}{prefix} - LUT Textures.asset";

            goboArray = SaveOrReplaceArray(goboArray, goboPath);
            lutArray = SaveOrReplaceArray(lutArray, lutPath);
            AssetDatabase.SaveAssets();
            EditorGUIUtility.PingObject(lutArray);
        }

        private static void CopyCompressedSlice(
            Texture source,
            int resolution,
            TextureFormat format,
            Texture2DArray destination,
            int slice)
        {
            RenderTexture temporary = new RenderTexture(
                resolution,
                resolution,
                0,
                RenderTextureFormat.ARGBFloat);
            Texture2D texture = new Texture2D(
                resolution,
                resolution,
                TextureFormat.RGBAFloat,
                false,
                false);

            Graphics.Blit(source, temporary);
            RenderTexture previous = RenderTexture.active;
            RenderTexture.active = temporary;
            texture.ReadPixels(new Rect(0, 0, resolution, resolution), 0, 0);
            texture.Apply();
            RenderTexture.active = previous;
            temporary.Release();
            DestroyImmediate(temporary);

            EditorUtility.CompressTexture(texture, format, TextureCompressionQuality.Best);
            Graphics.CopyTexture(texture, 0, 0, destination, slice, 0);
            DestroyImmediate(texture);
        }

        private static Texture2DArray SaveOrReplaceArray(Texture2DArray generated, string path)
        {
            Texture2DArray existing = AssetDatabase.LoadAssetAtPath<Texture2DArray>(path);
            if (existing == null)
            {
                AssetDatabase.CreateAsset(generated, path);
                return generated;
            }

            EditorUtility.CopySerialized(generated, existing);
            EditorUtility.SetDirty(existing);
            DestroyImmediate(generated);
            return existing;
        }
    }
}
